"""add store management fields

Revision ID: 2d20d938c3dd
Revises:
Create Date: 2026-08-05 18:19:48.479320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d20d938c3dd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores", sa.Column("account_holder_name", sa.String(), nullable=True)
    )
    op.add_column("stores", sa.Column("bank_name", sa.String(), nullable=True))
    op.add_column("stores", sa.Column("account_number", sa.String(), nullable=True))
    op.add_column("stores", sa.Column("ifsc_code", sa.String(), nullable=True))
    op.add_column("stores", sa.Column("payment_invoice", sa.String(), nullable=True))
    op.add_column("stores", sa.Column("payment_date", sa.Date(), nullable=True))
    op.add_column("stores", sa.Column("store_username", sa.String(), nullable=True))
    op.add_column(
        "stores", sa.Column("store_password_encrypted", sa.Text(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_stores_store_username", "stores", ["store_username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stores", type_="unique")
    op.drop_column("stores", "store_password_encrypted")
    op.drop_column("stores", "store_username")
    op.drop_column("stores", "payment_date")
    op.drop_column("stores", "payment_invoice")
    op.drop_column("stores", "ifsc_code")
    op.drop_column("stores", "account_number")
    op.drop_column("stores", "bank_name")
    op.drop_constraint("uq_stores_store_username", "stores", type_="unique")
    # ### end Alembic commands ###
