"""add service complaints

Revision ID: e1e8f25bf918
Revises: 2d20d938c3dd
Create Date: 2026-08-06 18:06:30.420393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e8f25bf918'
down_revision: Union[str, None] = '2d20d938c3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=False),
    sa.Column('complaint_date', sa.Date(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('problem_category', sa.Enum('power_issue', 'massage_mechanism', 'motor_issue', 'remote_display', 'airbag_issue', 'recliner_issue', 'noise_vibration', 'payment_issue', 'electrical_issue', 'other', name='problemcategory'), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='servicepriority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='servicestatus'), nullable=False),
    sa.Column('technician_name', sa.String(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('actual_problem', sa.Text(), nullable=True),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chair_id'], ['chairs.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_complaints_chair_id'), 'service_complaints', ['chair_id'], unique=False)
    op.create_index(op.f('ix_service_complaints_id'), 'service_complaints', ['id'], unique=False)
    op.create_index(op.f('ix_service_complaints_store_id'), 'service_complaints', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_complaints_store_id'), table_name='service_complaints')
    op.drop_index(op.f('ix_service_complaints_id'), table_name='service_complaints')
    op.drop_index(op.f('ix_service_complaints_chair_id'), table_name='service_complaints')
    op.drop_table('service_complaints')
    # ### end Alembic commands ###
